/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CertificateAuthorityGetSignedCertificateResponse
 */
public class CertificateAuthorityGetSignedCertificateResponseTest {
    private final CertificateAuthorityGetSignedCertificateResponse model = new CertificateAuthorityGetSignedCertificateResponse();

    /**
     * Model tests for CertificateAuthorityGetSignedCertificateResponse
     */
    @Test
    public void testCertificateAuthorityGetSignedCertificateResponse() {
        // TODO: test CertificateAuthorityGetSignedCertificateResponse
    }

    /**
     * Test the property 'certificate'
     */
    @Test
    public void certificateTest() {
        // TODO: test certificate
    }

}
