/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ResourcesShowResourceDetailsResponsePolicyVersionsInner
 */
public class ResourcesShowResourceDetailsResponsePolicyVersionsInnerTest {
    private final ResourcesShowResourceDetailsResponsePolicyVersionsInner model = new ResourcesShowResourceDetailsResponsePolicyVersionsInner();

    /**
     * Model tests for ResourcesShowResourceDetailsResponsePolicyVersionsInner
     */
    @Test
    public void testResourcesShowResourceDetailsResponsePolicyVersionsInner() {
        // TODO: test ResourcesShowResourceDetailsResponsePolicyVersionsInner
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'policyText'
     */
    @Test
    public void policyTextTest() {
        // TODO: test policyText
    }

    /**
     * Test the property 'policySha256'
     */
    @Test
    public void policySha256Test() {
        // TODO: test policySha256
    }

    /**
     * Test the property 'finishedAt'
     */
    @Test
    public void finishedAtTest() {
        // TODO: test finishedAt
    }

    /**
     * Test the property 'clientIp'
     */
    @Test
    public void clientIpTest() {
        // TODO: test clientIp
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
