/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * HostFactoryCreateHostIdentityTokensRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class HostFactoryCreateHostIdentityTokensRequest {
  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  private String expiration;

  public static final String SERIALIZED_NAME_HOST_FACTORY = "host_factory";
  @SerializedName(SERIALIZED_NAME_HOST_FACTORY)
  private String hostFactory;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_CIDR = "cidr";
  @SerializedName(SERIALIZED_NAME_CIDR)
  private List<String> cidr = null;

  public HostFactoryCreateHostIdentityTokensRequest() {
  }

  public HostFactoryCreateHostIdentityTokensRequest expiration(String expiration) {
    
    
    
    
    this.expiration = expiration;
    return this;
  }

   /**
   * &#x60;ISO 8601 datetime&#x60; denoting a requested expiration time.
   * @return expiration
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2017-08-04T22:27:20+00:00", required = true, value = "`ISO 8601 datetime` denoting a requested expiration time.")

  public String getExpiration() {
    return expiration;
  }


  public void setExpiration(String expiration) {
    
    
    
    this.expiration = expiration;
  }


  public HostFactoryCreateHostIdentityTokensRequest hostFactory(String hostFactory) {
    
    
    
    
    this.hostFactory = hostFactory;
    return this;
  }

   /**
   * Fully qualified host factory ID
   * @return hostFactory
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "myorg:host_factory:hf-db", required = true, value = "Fully qualified host factory ID")

  public String getHostFactory() {
    return hostFactory;
  }


  public void setHostFactory(String hostFactory) {
    
    
    
    this.hostFactory = hostFactory;
  }


  public HostFactoryCreateHostIdentityTokensRequest count(Integer count) {
    
    
    
    
    this.count = count;
    return this;
  }

   /**
   * Number of host tokens to create
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "Number of host tokens to create")

  public Integer getCount() {
    return count;
  }


  public void setCount(Integer count) {
    
    
    
    this.count = count;
  }


  public HostFactoryCreateHostIdentityTokensRequest cidr(List<String> cidr) {
    
    
    
    
    this.cidr = cidr;
    return this;
  }

  public HostFactoryCreateHostIdentityTokensRequest addCidrItem(String cidrItem) {
    if (this.cidr == null) {
      this.cidr = new ArrayList<>();
    }
    this.cidr.add(cidrItem);
    return this;
  }

   /**
   * Number of host tokens to create
   * @return cidr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"127.0.0.1/32\"]", value = "Number of host tokens to create")

  public List<String> getCidr() {
    return cidr;
  }


  public void setCidr(List<String> cidr) {
    
    
    
    this.cidr = cidr;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the HostFactoryCreateHostIdentityTokensRequest instance itself
   */
  public HostFactoryCreateHostIdentityTokensRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HostFactoryCreateHostIdentityTokensRequest hostFactoryCreateHostIdentityTokensRequest = (HostFactoryCreateHostIdentityTokensRequest) o;
    return Objects.equals(this.expiration, hostFactoryCreateHostIdentityTokensRequest.expiration) &&
        Objects.equals(this.hostFactory, hostFactoryCreateHostIdentityTokensRequest.hostFactory) &&
        Objects.equals(this.count, hostFactoryCreateHostIdentityTokensRequest.count) &&
        Objects.equals(this.cidr, hostFactoryCreateHostIdentityTokensRequest.cidr)&&
        Objects.equals(this.additionalProperties, hostFactoryCreateHostIdentityTokensRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiration, hostFactory, count, cidr, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HostFactoryCreateHostIdentityTokensRequest {\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    hostFactory: ").append(toIndentedString(hostFactory)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    cidr: ").append(toIndentedString(cidr)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("expiration");
    openapiFields.add("host_factory");
    openapiFields.add("count");
    openapiFields.add("cidr");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("expiration");
    openapiRequiredFields.add("host_factory");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to HostFactoryCreateHostIdentityTokensRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!HostFactoryCreateHostIdentityTokensRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HostFactoryCreateHostIdentityTokensRequest is not found in the empty JSON string", HostFactoryCreateHostIdentityTokensRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HostFactoryCreateHostIdentityTokensRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      if (!jsonObj.get("host_factory").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `host_factory` to be a primitive type in the JSON string but got `%s`", jsonObj.get("host_factory").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("cidr") != null && !jsonObj.get("cidr").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `cidr` to be an array in the JSON string but got `%s`", jsonObj.get("cidr").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HostFactoryCreateHostIdentityTokensRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HostFactoryCreateHostIdentityTokensRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HostFactoryCreateHostIdentityTokensRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HostFactoryCreateHostIdentityTokensRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<HostFactoryCreateHostIdentityTokensRequest>() {
           @Override
           public void write(JsonWriter out, HostFactoryCreateHostIdentityTokensRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public HostFactoryCreateHostIdentityTokensRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             HostFactoryCreateHostIdentityTokensRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of HostFactoryCreateHostIdentityTokensRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of HostFactoryCreateHostIdentityTokensRequest
  * @throws IOException if the JSON string is invalid with respect to HostFactoryCreateHostIdentityTokensRequest
  */
  public static HostFactoryCreateHostIdentityTokensRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HostFactoryCreateHostIdentityTokensRequest.class);
  }

 /**
  * Convert an instance of HostFactoryCreateHostIdentityTokensRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

