/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * StatusAuthenticatorDetailsResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class StatusAuthenticatorDetailsResponse {
  public static final String SERIALIZED_NAME_INSTALLED = "installed";
  @SerializedName(SERIALIZED_NAME_INSTALLED)
  private List<String> installed = null;

  public static final String SERIALIZED_NAME_CONFIGURED = "configured";
  @SerializedName(SERIALIZED_NAME_CONFIGURED)
  private List<String> configured = null;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private List<String> enabled = null;

  public StatusAuthenticatorDetailsResponse() {
  }

  public StatusAuthenticatorDetailsResponse installed(List<String> installed) {
    
    
    
    
    this.installed = installed;
    return this;
  }

  public StatusAuthenticatorDetailsResponse addInstalledItem(String installedItem) {
    if (this.installed == null) {
      this.installed = new ArrayList<>();
    }
    this.installed.add(installedItem);
    return this;
  }

   /**
   * The authenticators installed on the Conjur server
   * @return installed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"authn\"]", value = "The authenticators installed on the Conjur server")

  public List<String> getInstalled() {
    return installed;
  }


  public void setInstalled(List<String> installed) {
    
    
    
    this.installed = installed;
  }


  public StatusAuthenticatorDetailsResponse configured(List<String> configured) {
    
    
    
    
    this.configured = configured;
    return this;
  }

  public StatusAuthenticatorDetailsResponse addConfiguredItem(String configuredItem) {
    if (this.configured == null) {
      this.configured = new ArrayList<>();
    }
    this.configured.add(configuredItem);
    return this;
  }

   /**
   * The authenticators configured on the Conjur server
   * @return configured
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"authn\"]", value = "The authenticators configured on the Conjur server")

  public List<String> getConfigured() {
    return configured;
  }


  public void setConfigured(List<String> configured) {
    
    
    
    this.configured = configured;
  }


  public StatusAuthenticatorDetailsResponse enabled(List<String> enabled) {
    
    
    
    
    this.enabled = enabled;
    return this;
  }

  public StatusAuthenticatorDetailsResponse addEnabledItem(String enabledItem) {
    if (this.enabled == null) {
      this.enabled = new ArrayList<>();
    }
    this.enabled.add(enabledItem);
    return this;
  }

   /**
   * The authenticators enabled on the Conjur server
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"authn\"]", value = "The authenticators enabled on the Conjur server")

  public List<String> getEnabled() {
    return enabled;
  }


  public void setEnabled(List<String> enabled) {
    
    
    
    this.enabled = enabled;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the StatusAuthenticatorDetailsResponse instance itself
   */
  public StatusAuthenticatorDetailsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusAuthenticatorDetailsResponse statusAuthenticatorDetailsResponse = (StatusAuthenticatorDetailsResponse) o;
    return Objects.equals(this.installed, statusAuthenticatorDetailsResponse.installed) &&
        Objects.equals(this.configured, statusAuthenticatorDetailsResponse.configured) &&
        Objects.equals(this.enabled, statusAuthenticatorDetailsResponse.enabled)&&
        Objects.equals(this.additionalProperties, statusAuthenticatorDetailsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(installed, configured, enabled, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusAuthenticatorDetailsResponse {\n");
    sb.append("    installed: ").append(toIndentedString(installed)).append("\n");
    sb.append("    configured: ").append(toIndentedString(configured)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("installed");
    openapiFields.add("configured");
    openapiFields.add("enabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to StatusAuthenticatorDetailsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!StatusAuthenticatorDetailsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StatusAuthenticatorDetailsResponse is not found in the empty JSON string", StatusAuthenticatorDetailsResponse.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("installed") != null && !jsonObj.get("installed").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `installed` to be an array in the JSON string but got `%s`", jsonObj.get("installed").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("configured") != null && !jsonObj.get("configured").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `configured` to be an array in the JSON string but got `%s`", jsonObj.get("configured").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("enabled") != null && !jsonObj.get("enabled").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `enabled` to be an array in the JSON string but got `%s`", jsonObj.get("enabled").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatusAuthenticatorDetailsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatusAuthenticatorDetailsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatusAuthenticatorDetailsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatusAuthenticatorDetailsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<StatusAuthenticatorDetailsResponse>() {
           @Override
           public void write(JsonWriter out, StatusAuthenticatorDetailsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public StatusAuthenticatorDetailsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             StatusAuthenticatorDetailsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of StatusAuthenticatorDetailsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of StatusAuthenticatorDetailsResponse
  * @throws IOException if the JSON string is invalid with respect to StatusAuthenticatorDetailsResponse
  */
  public static StatusAuthenticatorDetailsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatusAuthenticatorDetailsResponse.class);
  }

 /**
  * Convert an instance of StatusAuthenticatorDetailsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

