/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.HostFactoryCreateHostIdentityTokensRequest;
import com.konfigthis.client.model.HostFactoryCreateHostIdentityTokensResponseInner;
import com.konfigthis.client.model.HostFactoryCreateHostRequest;
import com.konfigthis.client.model.HostFactoryCreateHostResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HostFactoryApi
 */
@Disabled
public class HostFactoryApiTest {

    private static HostFactoryApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HostFactoryApi(apiClient);
    }

    /**
     * Creates a Host using the Host Factory.
     *
     * Creates a Host using the Host Factory and returns a JSON description of it.  Requires a host factory token, which can be created using the create tokens API. In practice, this token is usually provided automatically as part of Conjur integration with your host provisioning infrastructure.  Note: If the token was created with a CIDR restriction, you must make this API request from a whitelisted address. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createHostTest() throws ApiException {
        String id = null;
        String xRequestId = null;
        Object annotations = null;
        HostFactoryCreateHostResponse response = api.createHost(id)
                .xRequestId(xRequestId)
                .annotations(annotations)
                .execute();
        // TODO: test validations
    }

    /**
     * Creates one or more host identity tokens.
     *
     * Creates one or more tokens which can be used to bootstrap host identity. Responds with a JSON document containing the tokens and their restrictions.  If the tokens are created with a CIDR restriction, Conjur will only accept them from the whitelisted IP ranges.  ##### Permissions required # &#x60;execute&#x60; privilege on the Host Factory.\&quot; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createHostIdentityTokensTest() throws ApiException {
        String expiration = null;
        String hostFactory = null;
        String xRequestId = null;
        Integer count = null;
        List<String> cidr = null;
        List<HostFactoryCreateHostIdentityTokensResponseInner> response = api.createHostIdentityTokens(expiration, hostFactory)
                .xRequestId(xRequestId)
                .count(count)
                .cidr(cidr)
                .execute();
        // TODO: test validations
    }

    /**
     * Revokes a token, immediately disabling it.
     *
     * Revokes a token, immediately disabling it.  ##### Permissions required  &#x60;update&#x60; privilege on the host factory.\&quot; 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revokeTokenTest() throws ApiException {
        String token = null;
        String xRequestId = null;
        api.revokeToken(token)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

}
