/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicKeysApi
 */
@Disabled
public class PublicKeysApiTest {

    private static PublicKeysApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PublicKeysApi(apiClient);
    }

    /**
     * Shows all public keys for a resource.
     *
     * Shows all public keys for a resource as newline delimited string for compatibility with the authorized_keys SSH format. Returns an empty string if the resource does not exist, to prevent attackers from determining whether a resource exists. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showAllForResourceTest() throws ApiException {
        String account = null;
        String kind = null;
        String identifier = null;
        String xRequestId = null;
        String response = api.showAllForResource(account, kind, identifier)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

}
