/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.1
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.StatusAuthenticatorDetailsResponse;
import com.konfigthis.client.model.StatusConjurServerInfoResponse;
import com.konfigthis.client.model.StatusGetClientInfoResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatusApi
 */
@Disabled
public class StatusApiTest {

    private static StatusApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new StatusApi(apiClient);
    }

    /**
     * Details about which authenticators are on the Conjur Server
     *
     * Response contains three members: installed, configured, and enabled.  installed: The authenticator is implemented in Conjur and is available for configuration configured: The authenticator has a webservice in the DB that was loaded by policy enabled: The authenticator is enabled (in the DB or in the ENV) and is ready for authentication 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authenticatorDetailsTest() throws ApiException {
        String xRequestId = null;
        StatusAuthenticatorDetailsResponse response = api.authenticatorDetails()
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Details whether an authentication service has been configured properly
     *
     * Once the status webservice has been properly configured and the relevant user groups have been given permissions to access the status webservice, the users in those groups can check the status of the authenticator.  Supported Authenticators:   - Azure   - OIDC  Not Supported:   - AWS IAM   - Kubernetes   - LDAP  See [Conjur Documentation](https://docs.conjur.org/Latest/en/Content/Integrations/Authn-status.htm) for details on setting up the authenticator status webservice. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkAuthenticatorConfigurationTest() throws ApiException {
        String authenticator = null;
        String serviceId = null;
        String account = null;
        String xRequestId = null;
        api.checkAuthenticatorConfiguration(authenticator, serviceId, account)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Details whether an authentication service has been configured properly
     *
     * Once the status webservice has been properly configured and the relevant user groups have been given permissions to access the status webservice, the users in those groups can check the status of the authenticator.  This operation only supports the GCP authenticator  See [Conjur Documentation](https://docs.conjur.org/Latest/en/Content/Integrations/Authn-status.htm) for details on setting up the authenticator status webservice. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkAuthenticatorStatusTest() throws ApiException {
        String account = null;
        String xRequestId = null;
        StatusCheckAuthenticatorConfigurationResponse response = api.checkAuthenticatorStatus(account)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Health info about conjur
     *
     * You can request health checks against any cluster node using the Conjur API. These routes do not require authentication.  The health check attempts an internal HTTP or TCP connection to each Conjur Enterprise service. It also attempts a simple transaction against all internal databases. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkConjurHealthTest() throws ApiException {
        Object response = api.checkConjurHealth()
                .execute();
        // TODO: test validations
    }

    /**
     * Health info about a given Conjur Enterprise server
     *
     * Use the remote_health route to check the health of any Conjur Enterprise Server from any other Conjur Enterprise Server. With this route, you can check master health relative to a follower, or follower health relative to a standby, and so on. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkRemoteHealthTest() throws ApiException {
        String remote = null;
        Object response = api.checkRemoteHealth(remote)
                .execute();
        // TODO: test validations
    }

    /**
     * Basic information about the Conjur Enterprise server
     *
     * Information about the Conjur Enterprise node which was queried against.  Includes authenticator info, release/version info, configuration details, internal services, and role information. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void conjurServerInfoTest() throws ApiException {
        StatusConjurServerInfoResponse response = api.conjurServerInfo()
                .execute();
        // TODO: test validations
    }

    /**
     * Provides information about the client making an API request.
     *
     * WhoAmI provides information about the client making an API request. It can be used to help troubleshoot configuration by verifying authentication and the client IP address for audit and network access restrictions. For more information, see Host Attributes. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getClientInfoTest() throws ApiException {
        String xRequestId = null;
        StatusGetClientInfoResponse response = api.getClientInfo()
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

}
